#!/bin/bash

if [[ ! -z $1 ]] ; then
    #extract only $1 file
    GREP='^\./'$1'|'
else
    GREP='^\./.*|'
fi

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for row in $(grep $GREP text)
do
    FILENAME=$(echo $row | cut -d\| -f1)
    TEXT=$(echo $row | cut -d\| -f2)
    PACKAGE=$(echo $row | cut -d\| -f3 | awk '{print $1}')
    if [[ ! -d $PACKAGE ]]; then
        mkdir $PACKAGE
    fi
    if [[ -f $PACKAGE/$FILENAME ]] ; then
        continue
    else
        echo "$PACKAGE/$FILENAME don't exists!"
    fi
done
IFS=$SAVEIFS
