#!/bin/bash

for lang in en it ; do
    for dir in core extra ; do
        cd $lang/$dir
        zip -r ../../asterisk-sounds-$dir-$lang-$(cat .version).zip ./ --exclude .version
        cd ../..
    done
done
